#include "config.h"

const char* MDNS_NAME = "zap";        // mDNS name - device will be accessible as zap.local
const char* METER_SN = "zap";        // Serial number of the meter, this is hard coded in firmware but can be changed in some future release


// API Configuration
const char* API_URL = "https://api.srcful.dev/";
const char* DATA_URL = "https://mainnet.srcful.dev/gw/data/";

const char* PRIVATE_KEY_HEX = "";
const char* EXPECTED_PUBLIC_KEY_HEX = "";

// MQTT Configuration - Configure these according to your MQTT broker
const char* MQTT_SERVER = "emqx.srcful.dev";                    // MQTT broker hostname/IP (empty = disabled)
const uint16_t MQTT_PORT = 8883;                 // MQTT broker port (1883 for non-SSL, 8883 for SSL)
const bool MQTT_USE_SSL = true;                 // Use SSL/TLS connection
// Note: MQTT_USERNAME and MQTT_PASSWORD are set dynamically in main.cpp using device ID and JWT 

// CA Certificate for MQTT SSL/TLS connections
const char* MQTT_CA_CERT PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDiTCCAxCgAwIBAgISBQFMH63RIEsRMi5znUwzpUQ3MAoGCCqGSM49BAMDMDIx
CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
NTAeFw0yNTA4MDYxOTU2MjJaFw0yNTExMDQxOTU2MjFaMBoxGDAWBgNVBAMTD2Vt
cXguc3JjZnVsLmRldjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABB032mGj/nJp
jJhISHkRJ6WM6OKhWs7wHcRwAhFaC5PGZNaMsOg+9yDj+eCnPC9wtbBGX+s1UlwM
vHQNCZU/jpmjggIcMIICGDAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFCffkPIo6DbR
H96EUOMap+fBsHGIMB8GA1UdIwQYMBaAFJ8rX888IU+dBLftKyzExnCL0tcNMDIG
CCsGAQUFBwEBBCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL2U1LmkubGVuY3Iub3Jn
LzAaBgNVHREEEzARgg9lbXF4LnNyY2Z1bC5kZXYwEwYDVR0gBAwwCjAIBgZngQwB
AgEwLQYDVR0fBCYwJDAioCCgHoYcaHR0cDovL2U1LmMubGVuY3Iub3JnLzU2LmNy
bDCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB1AO08S9boBsKkogBX28sk4jgB31Ev
7cSGxXAPIN23Pj/gAAABmIEqV5wAAAQDAEYwRAIgTdhd9tK7Dop7w7ZcQGRj1xZV
KIY7eWC2crsQISPvEXwCICHHrkmfkGuSfU1j6W0FRMITr2axYPxeQwvSF+vjWbcY
AHYAGgT/SdBUHUCv9qDDv/HYxGcvTuzuI0BomGsXQC7ciX0AAAGYgSpflgAABAMA
RzBFAiBXwXAz7KwUsBJcJwWZ3Rkgl9AhtR0E6ItmVsxWV0OyiQIhAI+wysbVWioD
/PTQ8kK68gT4/47H4641TergOXL+gTxcMAoGCCqGSM49BAMDA2cAMGQCMHbTRW/s
3mt2y5o6oUwiRszVMtfa+Dhu7N5zeGmVPe9MBryrcIJlMamatg+z/izD0AIwBK4S
8YuPJ8bCiugG7rgOEGjisPPU5vJsmvb1LH9s07pbJvSNuohmIGTgKPb7eOI2
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEVzCCAj+gAwIBAgIRAIOPbGPOsTmMYgZigxXJ/d4wDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCRTUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQNCzqK
a2GOtu/cX1jnxkJFVKtj9mZhSAouWXW0gQI3ULc/FnncmOyhKJdyIBwsz9V8UiBO
VHhbhBRrwJCuhezAUUE8Wod/Bk3U/mDR+mwt4X2VEIiiCFQPmRpM5uoKrNijgfgw
gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSfK1/PPCFPnQS37SssxMZw
i9LXDTAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAH3KdNEVCQdqk0LKyuNImTKdRJY1C
2uw2SJajuhqkyGPY8C+zzsufZ+mgnhnq1A2KVQOSykOEnUbx1cy637rBAihx97r+
bcwbZM6sTDIaEriR/PLk6LKs9Be0uoVxgOKDcpG9svD33J+G9Lcfv1K9luDmSTgG
6XNFIN5vfI5gs/lMPyojEMdIzK9blcl2/1vKxO8WGCcjvsQ1nJ/Pwt8LQZBfOFyV
XP8ubAp/au3dc4EKWG9MO5zcx1qT9+NXRGdVWxGvmBFRAajciMfXME1ZuGmk3/GO
koAM7ZkjZmleyokP1LGzmfJcUd9s7eeu1/9/eg5XlXd/55GtYjAM+C4DG5i7eaNq
cm2F+yxYIPt6cbbtYVNJCGfHWqHEQ4FYStUyFnv8sjyqU8ypgZaNJ9aVcWSICLOI
E1/Qv/7oKsnZCWJ926wU6RqG1OYPGOi1zuABhLw61cuPVDT28nQS/e6z95cJXq0e
K1BcaJ6fJZsmbjRgD5p3mvEf5vdQM7MCEvU0tHbsx2I5mHHJoABHb8KVBgWp/lcX
GWiWaeOyB7RP+OfDtvi2OsapxXiV7vNVs7fMlrRjY1joKaqmmycnBvAq14AEbtyL
sVfOS66B8apkeFX2NY4XPEYV4ZSCe8VHPrdrERk2wILG3T/EGmSIkCYVUMSnjmJd
VQD9F6Na/+zmXCc=
-----END CERTIFICATE-----
)EOF";
